/**
 * Shared systemd unit and sudoers content generators.
 * Used by both the full installer (panel.js) and the redeploy flow (redeploy.js).
 */

/**
 * Generate the lamalibre-lamaste-serverd systemd service unit content.
 *
 * @param {{ installDir: string, configDir: string }} ctx
 * @returns {string}
 */
export function generateServiceUnit(ctx) {
  return `[Unit]
Description=Lamaste Panel Server
After=network.target

[Service]
Type=simple
User=lamaste
Group=lamaste
# Lets the panel hand the chisel authfile to the group chisel runs as.
SupplementaryGroups=lamaste-chisel
WorkingDirectory=${ctx.installDir}/serverd
ExecStart=/usr/bin/node src/index.js
Environment=NODE_ENV=production
Environment=CONFIG_FILE=${ctx.configDir}/panel.json
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=lamalibre-lamaste-serverd

# Security hardening
# Note: NoNewPrivileges is intentionally omitted — the panel uses sudo for
# the fixed commands and root-owned helpers listed in /etc/sudoers.d/lamaste
# (systemctl, nginx -t, lamaste-priv, lamaste-certbot, lamaste-cert-info).
ProtectHome=true
ReadWritePaths=${ctx.configDir} /var/www/lamaste
PrivateTmp=true

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Generate the lamaste sudoers file content.
 *
 * The panel runs as `lamaste`; this file is everything it may do as root.
 * Every rule is a fixed command line or a root-owned program that validates
 * its own arguments — no rule ends in, or contains, a wildcard. (A sudoers
 * `*` matches spaces, so a wildcard rule such as `mv /tmp/x-* /var/www/*`
 * also accepts `mv /tmp/x-a -t /etc/sudoers.d /var/www/y`.)
 *
 * What the panel does NOT need root for, and therefore has no rule for:
 * - its PKI (/etc/lamalibre/lamaste/pki, owned by lamaste — the panel is the CA),
 * - static sites (/var/www/lamaste, owned lamaste:www-data),
 * - Authelia's configuration (/etc/authelia, owned lamaste:lamaste-authelia),
 * - the chisel authfile and key (group lamaste-chisel, of which lamaste is a member).
 * Binaries, systemd units and service accounts are installed by create-lamaste,
 * which runs as root; the panel never writes a unit or a binary.
 *
 * @returns {string}
 */
export function generateSudoersContent() {
  return `# Lamaste serverd sudo rules — generated by create-lamaste; do not edit.
# Every rule is a fixed command line or a root-owned program that validates its
# own arguments. There are no wildcards: a sudoers \`*\` matches spaces too.

# --- systemctl: managed services ---
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl start nginx
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl stop nginx
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl restart nginx
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl reload nginx
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl start chisel
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl stop chisel
# Chisel reloads its authfile by itself. The panel restarts it only when a
# change revokes access (a removed or rotated credential, a withdrawn port
# grant) — \`try-restart\`, so a chisel stopped on purpose stays stopped.
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl restart chisel
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl try-restart chisel
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl enable chisel
# Disabled (with stop) when startup reconciliation cannot secure chisel, so a
# reboot does not start it on a stale authfile; re-enabled once it succeeds.
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl disable chisel
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl start authelia
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl stop authelia
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl restart authelia
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl reload authelia
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl enable authelia
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl enable certbot.timer
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl start certbot.timer
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl start lamalibre-lamaste-serverd
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl stop lamalibre-lamaste-serverd
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl restart lamalibre-lamaste-serverd
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl start lamalibre-lamaste-gatekeeper
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl stop lamalibre-lamaste-gatekeeper
lamaste ALL=(root) NOPASSWD: /usr/bin/systemctl restart lamalibre-lamaste-gatekeeper

# --- nginx config test ---
lamaste ALL=(root) NOPASSWD: /usr/sbin/nginx -t

# --- root-owned programs that validate their own arguments ---
# lamaste-priv: install/enable/remove the panel's nginx vhosts (every directive
# checked against an allow-list — nginx opens the files a vhost names as
# root), store a TOTP secret with Authelia's CLI as the Authelia user, and
# start a self-update (create-lamaste@<version>) in a transient unit.
lamaste ALL=(root) NOPASSWD: /usr/local/sbin/lamaste-priv
# Let's Encrypt: certbot and openssl with fixed flags, hostnames and email
# validated. See scripts/lamaste-certbot, scripts/lamaste-cert-info.
lamaste ALL=(root) NOPASSWD: /usr/local/sbin/lamaste-certbot
lamaste ALL=(root) NOPASSWD: /usr/local/sbin/lamaste-cert-info
`;
}

/**
 * Generate the lamalibre-lamaste-gatekeeper systemd service unit content.
 *
 * @param {{ installDir: string, configDir: string }} ctx
 * @returns {string}
 */
export function generateGatekeeperServiceUnit(ctx) {
  return `[Unit]
Description=Lamaste Gatekeeper — tunnel authorization service
After=network.target authelia.service

[Service]
Type=simple
User=lamaste
Group=lamaste
WorkingDirectory=${ctx.installDir}/gatekeeper
ExecStart=/usr/bin/node dist/server/index.js
Environment=NODE_ENV=production
Environment=LAMALIBRE_LAMASTE_DATA_DIR=${ctx.configDir}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=lamalibre-lamaste-gatekeeper

# Security hardening
ProtectHome=true
ReadWritePaths=${ctx.configDir}
PrivateTmp=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Root-owned sudoers wrapper scripts shipped in this package's scripts/
 * directory and installed to /usr/local/sbin. The sudoers rules reference
 * these absolute paths; each script validates its arguments and runs its
 * command with a fixed argument vector.
 */
export const SUDOERS_WRAPPERS = [
  { name: 'lamaste-priv', dest: '/usr/local/sbin/lamaste-priv', interpreter: 'node' },
  { name: 'lamaste-certbot', dest: '/usr/local/sbin/lamaste-certbot', interpreter: 'bash' },
  { name: 'lamaste-cert-info', dest: '/usr/local/sbin/lamaste-cert-info', interpreter: 'bash' },
];

/**
 * Wrappers earlier versions installed that no sudoers rule references any
 * more; create-lamaste removes them on upgrade. The panel signs agent CSRs
 * and renames PKI files itself: it owns the PKI directory and the CA key.
 */
export const RETIRED_SUDOERS_WRAPPERS = [
  '/usr/local/sbin/lamaste-sign-csr',
  '/usr/local/sbin/lamaste-pki-rename',
];

/**
 * The group the chisel server runs as. The 0640 chisel authfile (every
 * agent's tunnel password) belongs to it; the lamaste user is a member so the
 * panel can hand the file to the group without privileges. Must match
 * CHISEL_AUTHFILE_GROUP in @lamalibre/lamaste/server.
 */
export const CHISEL_GROUP = 'lamaste-chisel';

/** The system account Authelia runs as (see accounts.js). */
export const AUTHELIA_USER = 'lamaste-authelia';

export const CHISEL_BIN = '/usr/local/bin/chisel';
export const AUTHELIA_BIN = '/usr/local/bin/authelia';
export const CHISEL_UNIT_PATH = '/etc/systemd/system/chisel.service';
export const AUTHELIA_UNIT_PATH = '/etc/systemd/system/authelia.service';
export const AUTHELIA_CONFIG_DIR = '/etc/authelia';
export const AUTHELIA_LOG_DIR = '/var/log/authelia';
export const WEB_ROOT = '/var/www/lamaste';

/**
 * The chisel server unit. The authfile carries per-agent credentials and
 * port grants; chisel reloads it on change. The process runs as `nobody`
 * with group {@link CHISEL_GROUP}, the only group that can read the 0640
 * authfile and key the panel writes. `--keyfile` keeps the SSH host identity
 * stable across restarts.
 *
 * Installed by create-lamaste only; onboarding enables and starts it.
 *
 * @param {{ configDir: string }} ctx
 * @returns {string}
 */
export function generateChiselUnit(ctx) {
  return `[Unit]
Description=Chisel Tunnel Server
After=network.target

[Service]
Type=simple
User=nobody
Group=${CHISEL_GROUP}
ExecStart=${CHISEL_BIN} server --reverse --port 9090 --host 127.0.0.1 --keyfile ${ctx.configDir}/chisel-server.key --authfile ${ctx.configDir}/chisel-users
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=chisel

NoNewPrivileges=yes
CapabilityBoundingSet=
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictNamespaces=yes
LockPersonality=yes

[Install]
WantedBy=multi-user.target
`;
}

/**
 * The Authelia unit, after upstream's packaged unit: a dedicated
 * unprivileged account, files it creates readable by its group only, and a
 * read-only view of the system except its configuration directory (the
 * SQLite database and notification file live there) and its log directory.
 *
 * Installed by create-lamaste only; onboarding writes the configuration,
 * then enables and starts it.
 *
 * @returns {string}
 */
export function generateAutheliaUnit() {
  return `[Unit]
Description=Authelia Authentication Server
After=network.target

[Service]
Type=simple
User=${AUTHELIA_USER}
Group=${AUTHELIA_USER}
UMask=027
Environment=AUTHELIA_SERVER_DISABLE_HEALTHCHECK=true
ExecStart=${AUTHELIA_BIN} --config ${AUTHELIA_CONFIG_DIR}/configuration.yml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=authelia

NoNewPrivileges=yes
CapabilityBoundingSet=
ProtectSystem=strict
ReadWritePaths=${AUTHELIA_CONFIG_DIR} ${AUTHELIA_LOG_DIR}
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictNamespaces=yes
LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM

[Install]
WantedBy=multi-user.target
`;
}

/** sites-available name of the port-80 catch-all. */
export const HTTP_REDIRECT_SITE = 'lamalibre-lamaste-http-redirect';

/**
 * The port-80 catch-all: every plain-HTTP request is redirected to HTTPS on
 * the same host and path. Without it nothing listens on :80 and `http://`
 * links to the relay's hostnames are refused.
 *
 * It does not get in the way of Let's Encrypt: certbot's nginx authenticator
 * (`certonly --nginx`, and renewals) clones this default_server block per
 * hostname for the length of an HTTP-01 challenge, answers the challenge
 * path ahead of the redirect, and restores the file afterwards — verified
 * on Ubuntu 24.04 (nginx 1.24, certbot 2.9) for new names, names with an
 * existing 443 block, multi-name lineages, and forced renewals.
 */
export function generateHttpRedirectVhost() {
  return `# Managed by Lamaste — plain HTTP is redirected to HTTPS.
server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
`;
}
